version: 2
jobs:
  bundle_dependencies:
    working_directory: ~/react-native-td
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-native-td-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - react-native-td-{{ arch }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "npm $(node -v)"
      - run:
          name: Install dependencies
          command: 'npm install'
      - save_cache:
          key: react-native-td-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/react-native-td/node_modules
            - ~/.cache/yarn

  compile_source:
    working_directory: ~/react-native-td
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-native-td-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - react-native-td-{{ arch }}
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Compile TypeScript
          command: 'npm tsc'
      - run:
          name: Compile example module
          command: |
            cd ./example
            npm install
            npm tsc
            npm build:ios
            npm build:android

  deploy_to_npm:
    working_directory: ~/react-native-td
    docker:
      - image: circleci/node:8.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-native-td-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - react-native-td-{{ arch }}
      - run:
          name: Install dependencies
          command: 'npm install'
      - run:
          name: Compile TypeScript
          command: 'npm tsc'
      - run:
          name: Login to npm and publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - bundle_dependencies:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - compile_source:
          requires:
            - bundle_dependencies
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy_to_npm:
          requires:
            - compile_source
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/